# Current
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
        args: ['--maxkb=5000']
    -   id: mixed-line-ending
        args: ['--fix=auto']
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
        args: ['--line-length', '80']
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black", "--filter-files"]
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: ['--max-line-length=80', '--ignore=E402', '--ignore=W503']

# Incoming
# repos:
#   - repo: https://github.com/pre-commit/pre-commit-hooks
#     rev: v4.5.0
#     hooks:
#     -   id: check-added-large-files
#         args: ['--maxkb=5000']
#     -   id: check-json
#     -   id: check-toml
#     -   id: check-yaml
#     -   id: check-shebang-scripts-are-executable
#     -   id: debug-statements
#     -   id: mixed-line-ending
#         args: ['--fix=no']
#   - repo: https://github.com/charliermarsh/ruff-pre-commit
#     rev: v0.3.4
#     hooks:
#     -   id: ruff
#         args: [--select=C901, --select=E501]
#     -   id: ruff-format
#   - repo: https://github.com/pre-commit/mirrors-mypy
#     rev: v1.9.0
#     hooks:
#     -   id: mypy
#   - repo: https://github.com/commitizen-tools/commitizen
#     rev: v3.20.0
#     hooks:
#     -   id: commitizen
#     -   id: commitizen-branch
#         stages: [push]