name: hacx
channels:
  - conda-forge
  - defaults
dependencies:
  - annotated-types=0.6.0
  - anyio=4.2.0
  - asttokens=2.0.5
  - blas=1.0
  - bottleneck=1.3.7
  - bzip2=1.0.8
  - ca-certificates=2024.7.2
  - certifi=2024.7.4
  - cffi=1.16.0
  - cfgv=3.4.0
  - click=8.1.7
  - colorama=0.4.6
  - comm=0.2.1
  - debugpy=1.6.7
  - decorator=5.1.1
  - distlib=0.3.8
  - exceptiongroup=1.2.0
  - executing=0.8.3
  - fastapi=0.103.0
  - filelock=3.13.1
  - greenlet=3.0.1
  - h11=0.14.0
  - identify=2.5.5
  - idna=3.7
  - intel-openmp=2023.1.0
  - ipykernel=6.29.3
  - ipython=8.25.0
  - jedi=0.19.1
  - jupyter_client=8.6.0
  - jupyter_core=5.7.2
  - libffi=3.4.4
  - libsodium=1.0.18
  - matplotlib-inline=0.1.6
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - nest-asyncio=1.6.0
  - nodeenv=1.7.0
  - numexpr=2.8.7
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openssl=3.0.14
  - packaging=24.1
  - pandas=2.2.2
  - parso=0.8.3
  - pip=24.0
  - platformdirs=3.10.0
  - pre-commit=3.6.2
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - psutil=5.9.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pydantic=2.5.3
  - pydantic-core=2.14.6
  - pygments=2.15.1
  - python=3.10.14
  - python-dateutil=2.9.0post0
  - python-tzdata=2023.3
  - pytz=2024.1
  - pywin32=305
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - setuptools=72.1.0
  - six=1.16.0
  - sniffio=1.3.0
  - sqlalchemy=2.0.30
  - sqlite=3.45.3
  - stack_data=0.2.0
  - starlette=0.27.0
  - tbb=2021.8.0
  - tk=8.6.14
  - tornado=6.4.1
  - traitlets=5.14.3
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - tzdata=2024a
  - ukkonen=1.0.1
  - uvicorn=0.20.0
  - vc=14.40
  - virtualenv=20.26.1
  - vs2015_runtime=14.40.33807
  - wcwidth=0.2.5
  - wheel=0.43.0
  - xz=5.4.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zlib=1.2.13
  - pip:
      - absl-py==2.1.0
      - astunparse==1.6.3
      - beautifulsoup4==4.12.3
      - blinker==1.8.2
      - charset-normalizer==3.3.2
      - cssselect==1.2.0
      - feedfinder2==0.0.4
      - feedparser==6.0.11
      - flask==3.0.3
      - flatbuffers==24.3.25
      - fsspec==2024.6.1
      - gast==0.6.0
      - google-pasta==0.2.0
      - grpcio==1.65.5
      - h5py==3.11.0
      - huggingface-hub==0.24.6
      - itsdangerous==2.2.0
      - jieba3k==0.35.1
      - jinja2==3.1.4
      - joblib==1.4.2
      - keras==3.5.0
      - libclang==18.1.1
      - lxml==5.3.0
      - lxml-html-clean==0.2.0
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - mdurl==0.1.2
      - ml-dtypes==0.4.0
      - namex==0.0.8
      - newspaper3k==0.2.8
      - nltk==3.9.1
      - opt-einsum==3.3.0
      - optree==0.12.1
      - pillow==10.4.0
      - protobuf==4.25.4
      - regex==2024.7.24
      - requests==2.32.3
      - requests-file==2.1.0
      - rich==13.7.1
      - safetensors==0.4.4
      - sgmllib3k==1.0.0
      - soupsieve==2.6
      - tensorboard==2.17.1
      - tensorboard-data-server==0.7.2
      - tensorflow==2.17.0
      - tensorflow-intel==2.17.0
      - tensorflow-io-gcs-filesystem==0.31.0
      - termcolor==2.4.0
      - tf-keras==2.17.0
      - tinysegmenter==0.3
      - tldextract==5.1.2
      - tokenizers==0.19.1
      - tqdm==4.66.5
      - transformers==4.44.2
      - urllib3==2.2.2
      - werkzeug==3.0.3
      - wrapt==1.16.0
      - scikit-learn==1.5.1
      - seaborn
      - matplotlib
      - openai==0.28
      - python-dotenv
