name: hacx
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - sqlalchemy
  - pandas
  - pip=24.0
  - pre-commit=3.6.2
  - ipykernel=6.29.3
  - fastapi
  - uvicorn

  - pip:
    - requests
    - tensorflow
    - flask